<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="N3.AnalisadorFiscal.Domain\N3.AnalisadorFiscal.Domain.csproj" />
    <ProjectReference Include="N3.AnalisadorFiscal.Data\N3.AnalisadorFiscal.Data.csproj" />
    <ProjectReference Include="N3.AnalisadorFiscal.Sped\N3.AnalisadorFiscal.Sped.csproj" />
    <ProjectReference Include="N3.AnalisadorFiscal.Recebimentos\N3.AnalisadorFiscal.Recebimentos.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>n3-analisador-fiscal-web</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="N3.AnalisadorFiscal.Domain\**\*.cs" />
    <Compile Remove="N3.AnalisadorFiscal.Data\**\*.cs" />
    <Compile Remove="N3.AnalisadorFiscal.Sped\**\*.cs" />
    <Compile Remove="N3.AnalisadorFiscal.Recebimentos\**\*.cs" />
    <Compile Remove="tmp\**\*.cs" />
    <Content Remove="tmp\**" />
    <None Remove="tmp\**" />
    <EmbeddedResource Remove="tmp\**" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="MudBlazor" Version="9.6.0" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>
</Project>

