IF COL_LENGTH('dbo.EMPRESA', 'NOME_FANTASIA') IS NULL
    ALTER TABLE dbo.EMPRESA ADD NOME_FANTASIA VARCHAR(255) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'ATIVO') IS NULL
BEGIN
    ALTER TABLE dbo.EMPRESA ADD ATIVO BIT NOT NULL
        CONSTRAINT DF_EMPRESA_ATIVO DEFAULT 1 WITH VALUES;
END;

IF COL_LENGTH('dbo.EMPRESA', 'CERTIFICADO_THUMBPRINT') IS NULL
    ALTER TABLE dbo.EMPRESA ADD CERTIFICADO_THUMBPRINT VARCHAR(64) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'CERTIFICADO_STORE_LOCATION') IS NULL
    ALTER TABLE dbo.EMPRESA ADD CERTIFICADO_STORE_LOCATION VARCHAR(20) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'REGIME_TRIBUTARIO') IS NULL
    ALTER TABLE dbo.EMPRESA ADD REGIME_TRIBUTARIO VARCHAR(20) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'LOGOMARCA') IS NULL
    ALTER TABLE dbo.EMPRESA ADD LOGOMARCA VARBINARY(MAX) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'LOGOMARCA_CONTENT_TYPE') IS NULL
    ALTER TABLE dbo.EMPRESA ADD LOGOMARCA_CONTENT_TYPE VARCHAR(100) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'LOGOMARCA_NOME_ARQUIVO') IS NULL
    ALTER TABLE dbo.EMPRESA ADD LOGOMARCA_NOME_ARQUIVO VARCHAR(255) NULL;

IF COL_LENGTH('dbo.EMPRESA', 'DATA_ABERTURA') IS NULL ALTER TABLE dbo.EMPRESA ADD DATA_ABERTURA DATE NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CNAE_PRINCIPAL_CODIGO') IS NULL ALTER TABLE dbo.EMPRESA ADD CNAE_PRINCIPAL_CODIGO VARCHAR(10) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CNAE_PRINCIPAL_DESCRICAO') IS NULL ALTER TABLE dbo.EMPRESA ADD CNAE_PRINCIPAL_DESCRICAO VARCHAR(500) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CNAES_SECUNDARIOS') IS NULL ALTER TABLE dbo.EMPRESA ADD CNAES_SECUNDARIOS VARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'NATUREZA_JURIDICA') IS NULL ALTER TABLE dbo.EMPRESA ADD NATUREZA_JURIDICA VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'PORTE') IS NULL ALTER TABLE dbo.EMPRESA ADD PORTE VARCHAR(100) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'SITUACAO_CADASTRAL') IS NULL ALTER TABLE dbo.EMPRESA ADD SITUACAO_CADASTRAL VARCHAR(100) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'DATA_SITUACAO_CADASTRAL') IS NULL ALTER TABLE dbo.EMPRESA ADD DATA_SITUACAO_CADASTRAL DATE NULL;
IF COL_LENGTH('dbo.EMPRESA', 'MOTIVO_SITUACAO_CADASTRAL') IS NULL ALTER TABLE dbo.EMPRESA ADD MOTIVO_SITUACAO_CADASTRAL VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'SITUACAO_ESPECIAL') IS NULL ALTER TABLE dbo.EMPRESA ADD SITUACAO_ESPECIAL VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'DATA_SITUACAO_ESPECIAL') IS NULL ALTER TABLE dbo.EMPRESA ADD DATA_SITUACAO_ESPECIAL DATE NULL;
IF COL_LENGTH('dbo.EMPRESA', 'TIPO_LOGRADOURO') IS NULL ALTER TABLE dbo.EMPRESA ADD TIPO_LOGRADOURO VARCHAR(50) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'LOGRADOURO') IS NULL ALTER TABLE dbo.EMPRESA ADD LOGRADOURO VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'NUMERO') IS NULL ALTER TABLE dbo.EMPRESA ADD NUMERO VARCHAR(30) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'COMPLEMENTO') IS NULL ALTER TABLE dbo.EMPRESA ADD COMPLEMENTO VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CEP') IS NULL ALTER TABLE dbo.EMPRESA ADD CEP VARCHAR(8) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'BAIRRO') IS NULL ALTER TABLE dbo.EMPRESA ADD BAIRRO VARCHAR(150) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'MUNICIPIO') IS NULL ALTER TABLE dbo.EMPRESA ADD MUNICIPIO VARCHAR(150) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'EMAIL') IS NULL ALTER TABLE dbo.EMPRESA ADD EMAIL VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'TELEFONE') IS NULL ALTER TABLE dbo.EMPRESA ADD TELEFONE VARCHAR(100) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'ENTE_FEDERATIVO_RESPONSAVEL') IS NULL ALTER TABLE dbo.EMPRESA ADD ENTE_FEDERATIVO_RESPONSAVEL VARCHAR(255) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'SINCRONIZADO_EM') IS NULL ALTER TABLE dbo.EMPRESA ADD SINCRONIZADO_EM DATETIME2 NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CODIGO_EMPRESA_FOLHA_FORTES') IS NULL ALTER TABLE dbo.EMPRESA ADD CODIGO_EMPRESA_FOLHA_FORTES VARCHAR(20) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CODIGO_EMPRESA_FISCAL_FORTES') IS NULL ALTER TABLE dbo.EMPRESA ADD CODIGO_EMPRESA_FISCAL_FORTES VARCHAR(20) NULL;
IF COL_LENGTH('dbo.EMPRESA', 'CODIGO_EMPRESA_CONTABIL_FORTES') IS NULL ALTER TABLE dbo.EMPRESA ADD CODIGO_EMPRESA_CONTABIL_FORTES VARCHAR(20) NULL;

UPDATE dbo.EMPRESA
SET RAZAO_SOCIAL = 'FERNANDES BEZERRA LTDA - MATRIZ'
WHERE CNPJ = '21658337000160'
  AND RAZAO_SOCIAL <> 'FERNANDES BEZERRA LTDA - MATRIZ';
