/*
    Tabelas do modulo EFD Contribuicoes (PIS/COFINS).
    Usa os cadastros compartilhados ja existentes:
    EMPRESA, PARTICIPANTE, PRODUTO, UNIDADE_MEDIDA e SPED_ARQUIVO.
*/

IF OBJECT_ID('EFD_CONTRIB_C100', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_C100 (
        ID_CONTRIB_C100 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        ID_PARTICIPANTE INT NULL,
        IND_OPER CHAR(1) NULL,
        IND_EMIT CHAR(1) NULL,
        COD_PART NVARCHAR(60) NULL,
        COD_MOD NVARCHAR(2) NULL,
        COD_SIT NVARCHAR(2) NULL,
        SER NVARCHAR(20) NULL,
        NUM_DOC NVARCHAR(20) NULL,
        CHV_NFE NVARCHAR(44) NULL,
        DT_DOC DATE NULL,
        DT_E_S DATE NULL,
        VL_DOC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_DOC DEFAULT (0),
        VL_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_DESC DEFAULT (0),
        VL_MERC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_MERC DEFAULT (0),
        IND_FRT CHAR(1) NULL,
        VL_FRT DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_FRT DEFAULT (0),
        VL_SEG DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_SEG DEFAULT (0),
        VL_OUT_DA DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_OUT_DA DEFAULT (0),
        VL_BC_ICMS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_BC_ICMS DEFAULT (0),
        VL_ICMS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_ICMS DEFAULT (0),
        VL_BC_ICMS_ST DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_BC_ICMS_ST DEFAULT (0),
        VL_ICMS_ST DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_ICMS_ST DEFAULT (0),
        VL_IPI DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_IPI DEFAULT (0),
        VL_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_PIS DEFAULT (0),
        VL_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_COFINS DEFAULT (0),
        VL_PIS_ST DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_PIS_ST DEFAULT (0),
        VL_COFINS_ST DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C100_VL_COFINS_ST DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_C100_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO),
        CONSTRAINT FK_EFD_CONTRIB_C100_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
        CONSTRAINT FK_EFD_CONTRIB_C100_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID_PARTICIPANTE)
    );

    CREATE INDEX IX_EFD_CONTRIB_C100_ARQUIVO ON EFD_CONTRIB_C100(ID_ARQUIVO);
    CREATE INDEX IX_EFD_CONTRIB_C100_EMPRESA_DOC ON EFD_CONTRIB_C100(ID_EMPRESA, DT_DOC, IND_OPER);
    CREATE INDEX IX_EFD_CONTRIB_C100_CHV_NFE ON EFD_CONTRIB_C100(CHV_NFE);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_C170', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_C170 (
        ID_CONTRIB_C170 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_CONTRIB_C100 INT NOT NULL,
        ID_PRODUTO INT NULL,
        NUM_ITEM INT NULL,
        COD_ITEM NVARCHAR(60) NULL,
        DESCR_COMPL NVARCHAR(500) NULL,
        QTD DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_QTD DEFAULT (0),
        UNID NVARCHAR(20) NULL,
        VL_ITEM DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_ITEM DEFAULT (0),
        VL_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_DESC DEFAULT (0),
        CST_ICMS NVARCHAR(3) NULL,
        CFOP NVARCHAR(4) NULL,
        NAT_BC_CRED NVARCHAR(2) NULL,
        VL_BC_ICMS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_BC_ICMS DEFAULT (0),
        ALIQ_ICMS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_ICMS DEFAULT (0),
        VL_ICMS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_ICMS DEFAULT (0),
        VL_BC_ICMS_ST DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_BC_ICMS_ST DEFAULT (0),
        ALIQ_ST DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_ST DEFAULT (0),
        VL_ICMS_ST DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_ICMS_ST DEFAULT (0),
        IND_APUR NVARCHAR(1) NULL,
        CST_IPI NVARCHAR(2) NULL,
        COD_ENQ NVARCHAR(3) NULL,
        VL_BC_IPI DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_BC_IPI DEFAULT (0),
        ALIQ_IPI DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_IPI DEFAULT (0),
        VL_IPI DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_IPI DEFAULT (0),
        CST_PIS NVARCHAR(2) NULL,
        VL_BC_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_BC_PIS DEFAULT (0),
        ALIQ_PIS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_PIS DEFAULT (0),
        QUANT_BC_PIS DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_QUANT_BC_PIS DEFAULT (0),
        ALIQ_PIS_QUANT DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_PIS_QUANT DEFAULT (0),
        VL_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_PIS DEFAULT (0),
        CST_COFINS NVARCHAR(2) NULL,
        VL_BC_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_BC_COFINS DEFAULT (0),
        ALIQ_COFINS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_COFINS DEFAULT (0),
        QUANT_BC_COFINS DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_QUANT_BC_COFINS DEFAULT (0),
        ALIQ_COFINS_QUANT DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_ALIQ_COFINS_QUANT DEFAULT (0),
        VL_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C170_VL_COFINS DEFAULT (0),
        COD_CTA NVARCHAR(60) NULL,
        CONSTRAINT FK_EFD_CONTRIB_C170_C100 FOREIGN KEY (ID_CONTRIB_C100) REFERENCES EFD_CONTRIB_C100(ID_CONTRIB_C100),
        CONSTRAINT FK_EFD_CONTRIB_C170_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
    );

    CREATE INDEX IX_EFD_CONTRIB_C170_C100 ON EFD_CONTRIB_C170(ID_CONTRIB_C100);
    CREATE INDEX IX_EFD_CONTRIB_C170_PRODUTO ON EFD_CONTRIB_C170(ID_PRODUTO);
    CREATE INDEX IX_EFD_CONTRIB_C170_CST_PIS ON EFD_CONTRIB_C170(CST_PIS);
    CREATE INDEX IX_EFD_CONTRIB_C170_CST_COFINS ON EFD_CONTRIB_C170(CST_COFINS);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_C175', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_C175 (
        ID_CONTRIB_C175 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_CONTRIB_C100 INT NOT NULL,
        CFOP NVARCHAR(4) NULL,
        VL_OPR DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_VL_OPR DEFAULT (0),
        VL_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_VL_DESC DEFAULT (0),
        CST_PIS NVARCHAR(2) NULL,
        VL_BC_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_VL_BC_PIS DEFAULT (0),
        ALIQ_PIS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_ALIQ_PIS DEFAULT (0),
        QUANT_BC_PIS DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_QUANT_BC_PIS DEFAULT (0),
        ALIQ_PIS_QUANT DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_ALIQ_PIS_QUANT DEFAULT (0),
        VL_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_VL_PIS DEFAULT (0),
        CST_COFINS NVARCHAR(2) NULL,
        VL_BC_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_VL_BC_COFINS DEFAULT (0),
        ALIQ_COFINS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_ALIQ_COFINS DEFAULT (0),
        QUANT_BC_COFINS DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_QUANT_BC_COFINS DEFAULT (0),
        ALIQ_COFINS_QUANT DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_ALIQ_COFINS_QUANT DEFAULT (0),
        VL_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_C175_VL_COFINS DEFAULT (0),
        COD_CTA NVARCHAR(60) NULL,
        INFO_COMPL NVARCHAR(500) NULL,
        CONSTRAINT FK_EFD_CONTRIB_C175_C100 FOREIGN KEY (ID_CONTRIB_C100) REFERENCES EFD_CONTRIB_C100(ID_CONTRIB_C100)
    );

    CREATE INDEX IX_EFD_CONTRIB_C175_C100 ON EFD_CONTRIB_C175(ID_CONTRIB_C100);
    CREATE INDEX IX_EFD_CONTRIB_C175_CFOP ON EFD_CONTRIB_C175(CFOP);
    CREATE INDEX IX_EFD_CONTRIB_C175_CST_PIS ON EFD_CONTRIB_C175(CST_PIS);
    CREATE INDEX IX_EFD_CONTRIB_C175_CST_COFINS ON EFD_CONTRIB_C175(CST_COFINS);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_A100', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_A100 (
        ID_CONTRIB_A100 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        ID_EMPRESA INT NOT NULL,
        ID_PARTICIPANTE INT NULL,
        IND_OPER CHAR(1) NULL,
        IND_EMIT CHAR(1) NULL,
        COD_PART NVARCHAR(60) NULL,
        COD_SIT NVARCHAR(2) NULL,
        SER NVARCHAR(20) NULL,
        SUB NVARCHAR(20) NULL,
        NUM_DOC NVARCHAR(20) NULL,
        CHV_NFSE NVARCHAR(80) NULL,
        DT_DOC DATE NULL,
        DT_EXE_SERV DATE NULL,
        VL_DOC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_DOC DEFAULT (0),
        VL_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_DESC DEFAULT (0),
        VL_BC_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_BC_PIS DEFAULT (0),
        VL_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_PIS DEFAULT (0),
        VL_BC_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_BC_COFINS DEFAULT (0),
        VL_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_COFINS DEFAULT (0),
        VL_PIS_RET DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_PIS_RET DEFAULT (0),
        VL_COFINS_RET DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A100_VL_COFINS_RET DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_A100_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO),
        CONSTRAINT FK_EFD_CONTRIB_A100_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
        CONSTRAINT FK_EFD_CONTRIB_A100_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID_PARTICIPANTE)
    );

    CREATE INDEX IX_EFD_CONTRIB_A100_ARQUIVO ON EFD_CONTRIB_A100(ID_ARQUIVO);
    CREATE INDEX IX_EFD_CONTRIB_A100_EMPRESA_DOC ON EFD_CONTRIB_A100(ID_EMPRESA, DT_DOC, IND_OPER);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_A170', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_A170 (
        ID_CONTRIB_A170 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_CONTRIB_A100 INT NOT NULL,
        NUM_ITEM INT NULL,
        COD_ITEM NVARCHAR(60) NULL,
        DESCR_COMPL NVARCHAR(500) NULL,
        VL_ITEM DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_VL_ITEM DEFAULT (0),
        VL_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_VL_DESC DEFAULT (0),
        NAT_BC_CRED NVARCHAR(2) NULL,
        IND_ORIG_CRED NVARCHAR(1) NULL,
        CST_PIS NVARCHAR(2) NULL,
        VL_BC_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_VL_BC_PIS DEFAULT (0),
        ALIQ_PIS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_ALIQ_PIS DEFAULT (0),
        VL_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_VL_PIS DEFAULT (0),
        CST_COFINS NVARCHAR(2) NULL,
        VL_BC_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_VL_BC_COFINS DEFAULT (0),
        ALIQ_COFINS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_ALIQ_COFINS DEFAULT (0),
        VL_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_A170_VL_COFINS DEFAULT (0),
        COD_CTA NVARCHAR(60) NULL,
        CONSTRAINT FK_EFD_CONTRIB_A170_A100 FOREIGN KEY (ID_CONTRIB_A100) REFERENCES EFD_CONTRIB_A100(ID_CONTRIB_A100)
    );

    CREATE INDEX IX_EFD_CONTRIB_A170_A100 ON EFD_CONTRIB_A170(ID_CONTRIB_A100);
    CREATE INDEX IX_EFD_CONTRIB_A170_CST_PIS ON EFD_CONTRIB_A170(CST_PIS);
    CREATE INDEX IX_EFD_CONTRIB_A170_CST_COFINS ON EFD_CONTRIB_A170(CST_COFINS);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_M100', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_M100 (
        ID_CONTRIB_M100 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        COD_CRED NVARCHAR(3) NULL,
        IND_CRED_ORI NVARCHAR(1) NULL,
        VL_BC_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_BC_PIS DEFAULT (0),
        ALIQ_PIS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_ALIQ_PIS DEFAULT (0),
        QUANT_BC_PIS DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_QUANT_BC_PIS DEFAULT (0),
        ALIQ_PIS_QUANT DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_ALIQ_PIS_QUANT DEFAULT (0),
        VL_CRED DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_CRED DEFAULT (0),
        VL_AJUS_ACRES DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_AJUS_ACRES DEFAULT (0),
        VL_AJUS_REDUC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_AJUS_REDUC DEFAULT (0),
        VL_CRED_DIF DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_CRED_DIF DEFAULT (0),
        VL_CRED_DISP DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_CRED_DISP DEFAULT (0),
        IND_DESC_CRED NVARCHAR(1) NULL,
        VL_CRED_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_VL_CRED_DESC DEFAULT (0),
        SLD_CRED DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M100_SLD_CRED DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_M100_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO)
    );

    CREATE INDEX IX_EFD_CONTRIB_M100_ARQUIVO ON EFD_CONTRIB_M100(ID_ARQUIVO);
    CREATE INDEX IX_EFD_CONTRIB_M100_COD_CRED ON EFD_CONTRIB_M100(COD_CRED);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_M200', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_M200 (
        ID_CONTRIB_M200 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        VL_TOT_CONT_NC_PER DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_TOT_CONT_NC_PER DEFAULT (0),
        VL_TOT_CRED_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_TOT_CRED_DESC DEFAULT (0),
        VL_TOT_CRED_DESC_ANT DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_TOT_CRED_DESC_ANT DEFAULT (0),
        VL_TOT_CONT_NC_DEV DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_TOT_CONT_NC_DEV DEFAULT (0),
        VL_RET_NC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_RET_NC DEFAULT (0),
        VL_OUT_DED_NC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_OUT_DED_NC DEFAULT (0),
        VL_CONT_NC_REC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_CONT_NC_REC DEFAULT (0),
        VL_TOT_CONT_CUM_PER DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_TOT_CONT_CUM_PER DEFAULT (0),
        VL_RET_CUM DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_RET_CUM DEFAULT (0),
        VL_OUT_DED_CUM DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_OUT_DED_CUM DEFAULT (0),
        VL_CONT_CUM_REC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_CONT_CUM_REC DEFAULT (0),
        VL_TOT_CONT_REC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M200_VL_TOT_CONT_REC DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_M200_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO)
    );

    CREATE INDEX IX_EFD_CONTRIB_M200_ARQUIVO ON EFD_CONTRIB_M200(ID_ARQUIVO);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_M500', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_M500 (
        ID_CONTRIB_M500 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        COD_CRED NVARCHAR(3) NULL,
        IND_CRED_ORI NVARCHAR(1) NULL,
        VL_BC_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_BC_COFINS DEFAULT (0),
        ALIQ_COFINS DECIMAL(9, 4) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_ALIQ_COFINS DEFAULT (0),
        QUANT_BC_COFINS DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_QUANT_BC_COFINS DEFAULT (0),
        ALIQ_COFINS_QUANT DECIMAL(18, 6) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_ALIQ_COFINS_QUANT DEFAULT (0),
        VL_CRED DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_CRED DEFAULT (0),
        VL_AJUS_ACRES DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_AJUS_ACRES DEFAULT (0),
        VL_AJUS_REDUC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_AJUS_REDUC DEFAULT (0),
        VL_CRED_DIF DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_CRED_DIF DEFAULT (0),
        VL_CRED_DISP DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_CRED_DISP DEFAULT (0),
        IND_DESC_CRED NVARCHAR(1) NULL,
        VL_CRED_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_VL_CRED_DESC DEFAULT (0),
        SLD_CRED DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M500_SLD_CRED DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_M500_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO)
    );

    CREATE INDEX IX_EFD_CONTRIB_M500_ARQUIVO ON EFD_CONTRIB_M500(ID_ARQUIVO);
    CREATE INDEX IX_EFD_CONTRIB_M500_COD_CRED ON EFD_CONTRIB_M500(COD_CRED);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_M600', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_M600 (
        ID_CONTRIB_M600 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        VL_TOT_CONT_NC_PER DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_TOT_CONT_NC_PER DEFAULT (0),
        VL_TOT_CRED_DESC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_TOT_CRED_DESC DEFAULT (0),
        VL_TOT_CRED_DESC_ANT DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_TOT_CRED_DESC_ANT DEFAULT (0),
        VL_TOT_CONT_NC_DEV DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_TOT_CONT_NC_DEV DEFAULT (0),
        VL_RET_NC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_RET_NC DEFAULT (0),
        VL_OUT_DED_NC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_OUT_DED_NC DEFAULT (0),
        VL_CONT_NC_REC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_CONT_NC_REC DEFAULT (0),
        VL_TOT_CONT_CUM_PER DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_TOT_CONT_CUM_PER DEFAULT (0),
        VL_RET_CUM DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_RET_CUM DEFAULT (0),
        VL_OUT_DED_CUM DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_OUT_DED_CUM DEFAULT (0),
        VL_CONT_CUM_REC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_CONT_CUM_REC DEFAULT (0),
        VL_TOT_CONT_REC DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_M600_VL_TOT_CONT_REC DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_M600_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO)
    );

    CREATE INDEX IX_EFD_CONTRIB_M600_ARQUIVO ON EFD_CONTRIB_M600(ID_ARQUIVO);
END;
GO

IF OBJECT_ID('EFD_CONTRIB_RESUMO_CST', 'U') IS NULL
BEGIN
    CREATE TABLE EFD_CONTRIB_RESUMO_CST (
        ID_RESUMO_CST INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_ARQUIVO INT NOT NULL,
        IND_OPER CHAR(1) NULL,
        CFOP NVARCHAR(4) NULL,
        CST_PIS NVARCHAR(2) NULL,
        CST_COFINS NVARCHAR(2) NULL,
        VL_OPERACAO DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_RESUMO_CST_VL_OPERACAO DEFAULT (0),
        VL_BC_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_RESUMO_CST_VL_BC_PIS DEFAULT (0),
        VL_PIS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_RESUMO_CST_VL_PIS DEFAULT (0),
        VL_BC_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_RESUMO_CST_VL_BC_COFINS DEFAULT (0),
        VL_COFINS DECIMAL(18, 2) NOT NULL CONSTRAINT DF_EFD_CONTRIB_RESUMO_CST_VL_COFINS DEFAULT (0),
        CONSTRAINT FK_EFD_CONTRIB_RESUMO_CST_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES SPED_ARQUIVO(ID_ARQUIVO)
    );

    CREATE INDEX IX_EFD_CONTRIB_RESUMO_CST_ARQUIVO ON EFD_CONTRIB_RESUMO_CST(ID_ARQUIVO);
    CREATE INDEX IX_EFD_CONTRIB_RESUMO_CST_CFOP ON EFD_CONTRIB_RESUMO_CST(CFOP);
    CREATE INDEX IX_EFD_CONTRIB_RESUMO_CST_PIS_COFINS ON EFD_CONTRIB_RESUMO_CST(CST_PIS, CST_COFINS);
END;
GO
