IF OBJECT_ID('dbo.FAQ_ARTIGO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.FAQ_ARTIGO
    (
        ID_FAQ_ARTIGO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_FAQ_ARTIGO PRIMARY KEY,
        PERGUNTA NVARCHAR(500) NOT NULL,
        RESPOSTA NVARCHAR(MAX) NOT NULL,
        CATEGORIA NVARCHAR(100) NOT NULL CONSTRAINT DF_FAQ_ARTIGO_CATEGORIA DEFAULT N'Geral',
        PALAVRAS_CHAVE NVARCHAR(500) NULL,
        PUBLICADO BIT NOT NULL CONSTRAINT DF_FAQ_ARTIGO_PUBLICADO DEFAULT 1,
        ATIVO BIT NOT NULL CONSTRAINT DF_FAQ_ARTIGO_ATIVO DEFAULT 1,
        ORIGEM NVARCHAR(30) NOT NULL CONSTRAINT DF_FAQ_ARTIGO_ORIGEM DEFAULT N'Manual',
        REFERENCIA_EXTERNA NVARCHAR(300) NULL,
        URL_ORIGEM NVARCHAR(1000) NULL,
        AUTOR NVARCHAR(150) NULL,
        CRIADO_EM DATETIME2 NOT NULL CONSTRAINT DF_FAQ_ARTIGO_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        ATUALIZADO_EM DATETIME2 NOT NULL CONSTRAINT DF_FAQ_ARTIGO_ATUALIZADO_EM DEFAULT SYSUTCDATETIME(),
        TOTAL_UTIL INT NOT NULL CONSTRAINT DF_FAQ_ARTIGO_TOTAL_UTIL DEFAULT 0,
        TOTAL_NAO_UTIL INT NOT NULL CONSTRAINT DF_FAQ_ARTIGO_TOTAL_NAO_UTIL DEFAULT 0
    );

    CREATE INDEX IX_FAQ_ARTIGO_CONSULTA
        ON dbo.FAQ_ARTIGO (ATIVO, PUBLICADO, CATEGORIA, ATUALIZADO_EM);

    CREATE UNIQUE INDEX UX_FAQ_ARTIGO_ORIGEM_REFERENCIA
        ON dbo.FAQ_ARTIGO (ORIGEM, REFERENCIA_EXTERNA)
        WHERE REFERENCIA_EXTERNA IS NOT NULL;
END;
