-- Estrutura normalizada da folha importada do Fortes AC.
-- Os códigos originais foram preservados para permitir o futuro de/para.
IF OBJECT_ID('dbo.FOLHA_IMPORTACAO','U') IS NULL
CREATE TABLE dbo.FOLHA_IMPORTACAO (
    ID_FOLHA_IMPORTACAO INT IDENTITY PRIMARY KEY, ID_EMPRESA INT NOT NULL,
    CODIGO_EMPRESA_FORTES VARCHAR(20) NOT NULL, ANO INT NOT NULL, MES INT NOT NULL,
    SEQUENCIAL_FOLHA_FORTES INT NOT NULL, TIPO_FOLHA_FORTES INT NULL,
    TIPO_COMPETENCIA_FORTES VARCHAR(10) NULL, FOLHA_ENCERRADA BIT NOT NULL,
    IMPORTADO_EM DATETIME2 NOT NULL,
    CONSTRAINT FK_FOLHA_IMPORTACAO_EMPRESA FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
    CONSTRAINT UX_FOLHA_IMPORTACAO UNIQUE(ID_EMPRESA,ANO,MES)
);

IF OBJECT_ID('dbo.FOLHA_TRABALHADOR','U') IS NULL
CREATE TABLE dbo.FOLHA_TRABALHADOR (
    ID_FOLHA_TRABALHADOR INT IDENTITY PRIMARY KEY, ID_FOLHA_IMPORTACAO INT NOT NULL,
    CODIGO_TRABALHADOR_FORTES VARCHAR(30) NOT NULL, NOME VARCHAR(255) NOT NULL,
    CONSTRAINT FK_FOLHA_TRABALHADOR_IMPORTACAO FOREIGN KEY(ID_FOLHA_IMPORTACAO) REFERENCES FOLHA_IMPORTACAO(ID_FOLHA_IMPORTACAO) ON DELETE CASCADE,
    CONSTRAINT UX_FOLHA_TRABALHADOR UNIQUE(ID_FOLHA_IMPORTACAO,CODIGO_TRABALHADOR_FORTES)
);

IF OBJECT_ID('dbo.FOLHA_EVENTO','U') IS NULL
CREATE TABLE dbo.FOLHA_EVENTO (
    ID_FOLHA_EVENTO INT IDENTITY PRIMARY KEY, ID_FOLHA_IMPORTACAO INT NOT NULL,
    CODIGO_EVENTO_FORTES VARCHAR(20) NOT NULL, NOME VARCHAR(255) NOT NULL, TIPO_EVENTO_FORTES INT NOT NULL,
    CONSTRAINT FK_FOLHA_EVENTO_IMPORTACAO FOREIGN KEY(ID_FOLHA_IMPORTACAO) REFERENCES FOLHA_IMPORTACAO(ID_FOLHA_IMPORTACAO) ON DELETE CASCADE,
    CONSTRAINT UX_FOLHA_EVENTO UNIQUE(ID_FOLHA_IMPORTACAO,CODIGO_EVENTO_FORTES)
);

IF OBJECT_ID('dbo.FOLHA_LANCAMENTO','U') IS NULL
CREATE TABLE dbo.FOLHA_LANCAMENTO (
    ID_FOLHA_LANCAMENTO BIGINT IDENTITY PRIMARY KEY, ID_FOLHA_IMPORTACAO INT NOT NULL,
    ID_FOLHA_TRABALHADOR INT NOT NULL, ID_FOLHA_EVENTO INT NOT NULL,
    REFERENCIA DECIMAL(18,4) NOT NULL, VALOR DECIMAL(18,2) NOT NULL,
    PARAMETRO DECIMAL(18,4) NOT NULL, ATRIBUTO VARCHAR(30) NULL, DEMONSTRACAO VARCHAR(30) NULL,
    CONSTRAINT FK_FOLHA_LANCAMENTO_IMPORTACAO FOREIGN KEY(ID_FOLHA_IMPORTACAO) REFERENCES FOLHA_IMPORTACAO(ID_FOLHA_IMPORTACAO) ON DELETE CASCADE,
    CONSTRAINT FK_FOLHA_LANCAMENTO_TRABALHADOR FOREIGN KEY(ID_FOLHA_TRABALHADOR) REFERENCES FOLHA_TRABALHADOR(ID_FOLHA_TRABALHADOR),
    CONSTRAINT FK_FOLHA_LANCAMENTO_EVENTO FOREIGN KEY(ID_FOLHA_EVENTO) REFERENCES FOLHA_EVENTO(ID_FOLHA_EVENTO)
);

IF OBJECT_ID('dbo.FOLHA_RESUMO_ENCARGOS','U') IS NULL
CREATE TABLE dbo.FOLHA_RESUMO_ENCARGOS (
    ID_FOLHA_IMPORTACAO INT PRIMARY KEY,
    INSS_PATRONAL DECIMAL(18,2) NOT NULL,
    FGTS DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_FOLHA_RESUMO_IMPORTACAO FOREIGN KEY(ID_FOLHA_IMPORTACAO)
        REFERENCES FOLHA_IMPORTACAO(ID_FOLHA_IMPORTACAO) ON DELETE CASCADE
);
