IF OBJECT_ID('dbo.NFSE_DOCUMENTO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NFSE_DOCUMENTO
    (
        ID_NFSE BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_NFSE_DOCUMENTO PRIMARY KEY,
        ID_EMPRESA INT NOT NULL,
        NSU BIGINT NOT NULL,
        CHAVE_ACESSO VARCHAR(60) NOT NULL,
        NUMERO_NOTA VARCHAR(30) NULL,
        DATA_EMISSAO DATETIME2 NOT NULL,
        COMPETENCIA DATE NOT NULL,
        CNPJ_PRESTADOR VARCHAR(14) NOT NULL,
        NOME_PRESTADOR VARCHAR(255) NULL,
        CNPJ_TOMADOR VARCHAR(14) NULL,
        NOME_TOMADOR VARCHAR(255) NULL,
        CODIGO_SERVICO VARCHAR(20) NULL,
        MUNICIPIO_INCIDENCIA VARCHAR(7) NULL,
        VALOR_SERVICOS DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_VALOR_SERVICOS DEFAULT 0,
        BASE_CALCULO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_BASE_CALCULO DEFAULT 0,
        ALIQUOTA DECIMAL(9,4) NOT NULL CONSTRAINT DF_NFSE_ALIQUOTA DEFAULT 0,
        VALOR_ISS DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_VALOR_ISS DEFAULT 0,
        VALOR_PIS_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_PIS_RET DEFAULT 0,
        VALOR_COFINS_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_COFINS_RET DEFAULT 0,
        VALOR_IRRF_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_IRRF_RET DEFAULT 0,
        VALOR_CSLL_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_CSLL_RET DEFAULT 0,
        VALOR_INSS_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_INSS_RET DEFAULT 0,
        ISS_RETIDO BIT NOT NULL CONSTRAINT DF_NFSE_ISS_RETIDO DEFAULT 0,
        CANCELADA BIT NOT NULL CONSTRAINT DF_NFSE_CANCELADA DEFAULT 0,
        XML_DOCUMENTO XML NOT NULL,
        CRIADO_EM DATETIME2 NOT NULL CONSTRAINT DF_NFSE_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        ATUALIZADO_EM DATETIME2 NULL,
        CONSTRAINT FK_NFSE_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES dbo.EMPRESA(ID_EMPRESA),
        CONSTRAINT UQ_NFSE_EMPRESA_CHAVE UNIQUE (ID_EMPRESA, CHAVE_ACESSO),
        CONSTRAINT UQ_NFSE_EMPRESA_NSU UNIQUE (ID_EMPRESA, NSU)
    );

    CREATE INDEX IX_NFSE_APURACAO ON dbo.NFSE_DOCUMENTO
        (ID_EMPRESA, COMPETENCIA, CANCELADA)
        INCLUDE (CNPJ_PRESTADOR, CNPJ_TOMADOR, VALOR_SERVICOS, VALOR_ISS, ISS_RETIDO);
END;

IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'NUMERO_NOTA') IS NULL
    ALTER TABLE dbo.NFSE_DOCUMENTO ADD NUMERO_NOTA VARCHAR(30) NULL;

IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'NOME_PRESTADOR') IS NULL
    ALTER TABLE dbo.NFSE_DOCUMENTO ADD NOME_PRESTADOR VARCHAR(255) NULL;

IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'VALOR_PIS_RETIDO') IS NULL ALTER TABLE dbo.NFSE_DOCUMENTO ADD VALOR_PIS_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_PIS_RET DEFAULT 0 WITH VALUES;
IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'VALOR_COFINS_RETIDO') IS NULL ALTER TABLE dbo.NFSE_DOCUMENTO ADD VALOR_COFINS_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_COFINS_RET DEFAULT 0 WITH VALUES;
IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'VALOR_IRRF_RETIDO') IS NULL ALTER TABLE dbo.NFSE_DOCUMENTO ADD VALOR_IRRF_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_IRRF_RET DEFAULT 0 WITH VALUES;
IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'VALOR_CSLL_RETIDO') IS NULL ALTER TABLE dbo.NFSE_DOCUMENTO ADD VALOR_CSLL_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_CSLL_RET DEFAULT 0 WITH VALUES;
IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'VALOR_INSS_RETIDO') IS NULL ALTER TABLE dbo.NFSE_DOCUMENTO ADD VALOR_INSS_RETIDO DECIMAL(18,2) NOT NULL CONSTRAINT DF_NFSE_INSS_RET DEFAULT 0 WITH VALUES;

IF COL_LENGTH('dbo.NFSE_DOCUMENTO', 'NOME_TOMADOR') IS NULL
    ALTER TABLE dbo.NFSE_DOCUMENTO ADD NOME_TOMADOR VARCHAR(255) NULL;

IF OBJECT_ID('dbo.NFSE_SINCRONIZACAO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NFSE_SINCRONIZACAO
    (
        ID_EMPRESA INT NOT NULL CONSTRAINT PK_NFSE_SINCRONIZACAO PRIMARY KEY,
        ULTIMO_NSU BIGINT NOT NULL CONSTRAINT DF_NFSE_SINC_NSU DEFAULT 0,
        ATUALIZADO_EM DATETIME2 NOT NULL CONSTRAINT DF_NFSE_SINC_DATA DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_NFSE_SINC_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES dbo.EMPRESA(ID_EMPRESA)
    );
END;
