/* Uploads independentes usados exclusivamente na pré-análise de ICMS. */
IF OBJECT_ID('PRE_ANALISE_SPED', 'U') IS NULL
BEGIN
    CREATE TABLE PRE_ANALISE_SPED (
        ID_PRE_ANALISE_SPED INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NOME_ARQUIVO NVARCHAR(260) NOT NULL,
        HASH_ARQUIVO NVARCHAR(64) NOT NULL,
        CNPJ NVARCHAR(14) NULL,
        RAZAO_SOCIAL NVARCHAR(200) NULL,
        UF NVARCHAR(2) NULL,
        DT_INI DATE NULL,
        DT_FIN DATE NULL,
        STATUS NVARCHAR(30) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_STATUS DEFAULT ('IMPORTADO'),
        IMPORTADO_EM DATETIME2 NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_DATA DEFAULT (SYSUTCDATETIME()),
        TOTAL_NOTAS_ENTRADA INT NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_NOTAS DEFAULT (0),
        VALOR_TOTAL_NOTAS DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_VALOR DEFAULT (0),
        BASE_ICMS_TOTAL DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_BASE DEFAULT (0),
        ICMS_CREDITO_TOTAL DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_ICMS DEFAULT (0)
    );
    CREATE INDEX IX_PRE_ANALISE_SPED_HASH ON PRE_ANALISE_SPED(HASH_ARQUIVO);
END;
GO

IF OBJECT_ID('PRE_ANALISE_SPED_NOTA', 'U') IS NULL
BEGIN
    CREATE TABLE PRE_ANALISE_SPED_NOTA (
        ID_PRE_ANALISE_SPED_NOTA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_PRE_ANALISE_SPED INT NOT NULL,
        COD_PART NVARCHAR(60) NULL,
        NOME_PARTICIPANTE NVARCHAR(200) NULL,
        CNPJ_PARTICIPANTE NVARCHAR(14) NULL,
        COD_MOD NVARCHAR(2) NULL,
        COD_SIT NVARCHAR(2) NULL,
        SER NVARCHAR(20) NULL,
        NUM_DOC NVARCHAR(20) NULL,
        CHV_NFE NVARCHAR(44) NULL,
        DT_DOC DATE NULL,
        DT_ENTRADA DATE NULL,
        VL_DOC DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_NOTA_DOC DEFAULT (0),
        VL_MERC DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_NOTA_MERC DEFAULT (0),
        VL_BC_ICMS DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_NOTA_BASE DEFAULT (0),
        VL_ICMS DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_NOTA_ICMS DEFAULT (0),
        STATUS_ANALISE NVARCHAR(30) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_NOTA_STATUS DEFAULT ('PENDENTE'),
        OBSERVACAO NVARCHAR(2000) NULL,
        CONSTRAINT FK_PRE_ANALISE_SPED_NOTA_ARQUIVO FOREIGN KEY (ID_PRE_ANALISE_SPED)
            REFERENCES PRE_ANALISE_SPED(ID_PRE_ANALISE_SPED) ON DELETE CASCADE
    );
    CREATE INDEX IX_PRE_ANALISE_SPED_NOTA_ARQUIVO ON PRE_ANALISE_SPED_NOTA(ID_PRE_ANALISE_SPED);
    CREATE INDEX IX_PRE_ANALISE_SPED_NOTA_CHAVE ON PRE_ANALISE_SPED_NOTA(CHV_NFE);
END;
GO

IF OBJECT_ID('PRE_ANALISE_SPED_ITEM', 'U') IS NULL
BEGIN
    CREATE TABLE PRE_ANALISE_SPED_ITEM (
        ID_PRE_ANALISE_SPED_ITEM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ID_PRE_ANALISE_SPED_NOTA INT NOT NULL,
        NUM_ITEM INT NULL,
        COD_ITEM NVARCHAR(60) NULL,
        DESCRICAO NVARCHAR(500) NULL,
        CFOP NVARCHAR(4) NULL,
        CST_ICMS NVARCHAR(3) NULL,
        VL_ITEM DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_ITEM_VALOR DEFAULT (0),
        VL_BC_ICMS DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_ITEM_BASE DEFAULT (0),
        ALIQ_ICMS DECIMAL(9,4) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_ITEM_ALIQ DEFAULT (0),
        VL_ICMS DECIMAL(18,2) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_ITEM_ICMS DEFAULT (0),
        CLASSIFICACAO NVARCHAR(50) NOT NULL CONSTRAINT DF_PRE_ANALISE_SPED_ITEM_CLASS DEFAULT ('PENDENTE'),
        JUSTIFICATIVA NVARCHAR(2000) NULL,
        CONSTRAINT FK_PRE_ANALISE_SPED_ITEM_NOTA FOREIGN KEY (ID_PRE_ANALISE_SPED_NOTA)
            REFERENCES PRE_ANALISE_SPED_NOTA(ID_PRE_ANALISE_SPED_NOTA) ON DELETE CASCADE
    );
    CREATE INDEX IX_PRE_ANALISE_SPED_ITEM_NOTA ON PRE_ANALISE_SPED_ITEM(ID_PRE_ANALISE_SPED_NOTA);
END;
GO

IF OBJECT_ID('PRE_ANALISE_REGRA_ITEM', 'U') IS NULL
BEGIN
    CREATE TABLE PRE_ANALISE_REGRA_ITEM (
        ID_PRE_ANALISE_REGRA_ITEM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CODIGO NVARCHAR(60) NOT NULL,
        NOME NVARCHAR(200) NOT NULL,
        UF_DESTINO NVARCHAR(2) NULL,
        CNPJ_FORNECEDOR NVARCHAR(200) NULL,
        NCM_PREFIXO NVARCHAR(8) NULL,
        NCM_EXCECOES NVARCHAR(200) NULL,
        TERMOS_DESCRICAO NVARCHAR(1000) NULL,
        CSTS_APLICAVEIS NVARCHAR(200) NULL,
        CFOPS_APLICAVEIS NVARCHAR(500) NULL,
        RESULTADO NVARCHAR(50) NOT NULL,
        PERCENTUAL_CREDITO DECIMAL(9,4) NULL,
        PRIORIDADE INT NOT NULL CONSTRAINT DF_PRE_ANALISE_REGRA_PRIORIDADE DEFAULT (100),
        FUNDAMENTO_LEGAL NVARCHAR(1000) NULL,
        VIGENCIA_INICIAL DATE NOT NULL,
        VIGENCIA_FINAL DATE NULL,
        ATIVA BIT NOT NULL CONSTRAINT DF_PRE_ANALISE_REGRA_ATIVA DEFAULT (1),
        CONSTRAINT UQ_PRE_ANALISE_REGRA_ITEM_CODIGO UNIQUE (CODIGO)
    );
    CREATE INDEX IX_PRE_ANALISE_REGRA_ITEM_VIGENCIA
        ON PRE_ANALISE_REGRA_ITEM(ATIVA, UF_DESTINO, VIGENCIA_INICIAL, VIGENCIA_FINAL);
END;
GO

IF COL_LENGTH('PRE_ANALISE_REGRA_ITEM', 'CNPJ_FORNECEDOR') IS NULL
    ALTER TABLE PRE_ANALISE_REGRA_ITEM ADD CNPJ_FORNECEDOR NVARCHAR(200) NULL;
GO

IF COL_LENGTH('PRE_ANALISE_SPED_ITEM', 'NCM') IS NULL
    ALTER TABLE PRE_ANALISE_SPED_ITEM ADD NCM NVARCHAR(8) NULL;
GO
IF COL_LENGTH('PRE_ANALISE_SPED_ITEM', 'CEST') IS NULL
    ALTER TABLE PRE_ANALISE_SPED_ITEM ADD CEST NVARCHAR(7) NULL;
GO
IF COL_LENGTH('PRE_ANALISE_SPED_ITEM', 'ID_PRE_ANALISE_REGRA_ITEM') IS NULL
    ALTER TABLE PRE_ANALISE_SPED_ITEM ADD ID_PRE_ANALISE_REGRA_ITEM INT NULL;
GO
IF COL_LENGTH('PRE_ANALISE_SPED_ITEM', 'NIVEL_CONFIANCA') IS NULL
    ALTER TABLE PRE_ANALISE_SPED_ITEM ADD NIVEL_CONFIANCA NVARCHAR(20) NULL;
GO
IF COL_LENGTH('PRE_ANALISE_SPED_ITEM', 'CREDITO_PERMITIDO') IS NULL
    ALTER TABLE PRE_ANALISE_SPED_ITEM ADD CREDITO_PERMITIDO DECIMAL(18,2) NULL;
GO
IF COL_LENGTH('PRE_ANALISE_SPED_ITEM', 'DIFERENCA_CREDITO') IS NULL
    ALTER TABLE PRE_ANALISE_SPED_ITEM ADD DIFERENCA_CREDITO DECIMAL(18,2) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM PRE_ANALISE_REGRA_ITEM WHERE CODIGO = 'PNEUS_ST_RN')
BEGIN
    INSERT INTO PRE_ANALISE_REGRA_ITEM
        (CODIGO,NOME,UF_DESTINO,NCM_PREFIXO,NCM_EXCECOES,TERMOS_DESCRICAO,RESULTADO,
         PERCENTUAL_CREDITO,PRIORIDADE,FUNDAMENTO_LEGAL,VIGENCIA_INICIAL,ATIVA)
    VALUES
        ('PNEUS_ST_RN',N'Pneumáticos novos sujeitos a ST no RN','RN','4011','401150',
         'PNEU;PNEUMATICO','SEM_CREDITO_ST',0,10,
         N'RICMS/RN, Decreto 31.825/2022, Anexo 007, art. 14; Convênio ICMS 142/2018.',
         '2022-11-01',1);
END;
GO

IF NOT EXISTS (SELECT 1 FROM PRE_ANALISE_REGRA_ITEM WHERE CODIGO = 'CAMARAS_AR_ST_RN')
BEGIN
    INSERT INTO PRE_ANALISE_REGRA_ITEM
        (CODIGO,NOME,UF_DESTINO,NCM_PREFIXO,NCM_EXCECOES,TERMOS_DESCRICAO,RESULTADO,
         PERCENTUAL_CREDITO,PRIORIDADE,FUNDAMENTO_LEGAL,VIGENCIA_INICIAL,ATIVA)
    VALUES
        ('CAMARAS_AR_ST_RN',N'Câmaras de ar de borracha sujeitas a ST no RN','RN','4013','401320',
         'CAMARA DE AR;CAMARA AR','SEM_CREDITO_ST',0,20,
         N'RICMS/RN, Decreto 31.825/2022, Anexo 007, art. 14; Convênio ICMS 142/2018.',
         '2022-11-01',1);
END;
GO

UPDATE PRE_ANALISE_REGRA_ITEM
SET NOME = N'Pneumáticos novos sujeitos a ST no RN',
    FUNDAMENTO_LEGAL = N'RICMS/RN, Decreto 31.825/2022, Anexo 007, art. 14; Convênio ICMS 142/2018.'
WHERE CODIGO = 'PNEUS_ST_RN';
GO

UPDATE PRE_ANALISE_REGRA_ITEM
SET NOME = N'Câmaras de ar de borracha sujeitas a ST no RN',
    FUNDAMENTO_LEGAL = N'RICMS/RN, Decreto 31.825/2022, Anexo 007, art. 14; Convênio ICMS 142/2018.'
WHERE CODIGO = 'CAMARAS_AR_ST_RN';
GO

;WITH REGRAS_FORNECEDOR AS (
    SELECT * FROM (VALUES
        ('FORN_COMERCIAL_NOBRE_SEM_CREDITO',N'Comercial Nobre - sem direito a crédito','01760557000193',NULL,'SEM_CREDITO',CAST(0 AS DECIMAL(9,4)),5),
        ('FORN_THIAGO_DANTAS_SEM_CREDITO',N'Thiago Dantas Costa ME - sem direito a crédito','05031386000176;15031386000176',NULL,'SEM_CREDITO',CAST(0 AS DECIMAL(9,4)),5),
        ('FORN_BRANDAO_NCM_28151100_SEM_CREDITO',N'Brandão Sintéticos - exceção sem crédito para NCM 28151100','12659486000153','28151100','SEM_CREDITO',CAST(0 AS DECIMAL(9,4)),6),
        ('FORN_RCL_QUIMICA_CREDITO_12',N'R C L Química - crédito de 12% nos itens não ST','53479131000160',NULL,'CREDITO_PERMITIDO',CAST(12 AS DECIMAL(9,4)),500),
        ('FORN_BRANDAO_CREDITO_12',N'Brandão Sintéticos - crédito de 12% nos itens não ST','12659486000153',NULL,'CREDITO_PERMITIDO',CAST(12 AS DECIMAL(9,4)),500)
    ) V(CODIGO,NOME,CNPJ_FORNECEDOR,NCM_PREFIXO,RESULTADO,PERCENTUAL_CREDITO,PRIORIDADE)
)
INSERT INTO PRE_ANALISE_REGRA_ITEM
    (CODIGO,NOME,UF_DESTINO,CNPJ_FORNECEDOR,NCM_PREFIXO,RESULTADO,PERCENTUAL_CREDITO,
     PRIORIDADE,FUNDAMENTO_LEGAL,VIGENCIA_INICIAL,ATIVA)
SELECT R.CODIGO,R.NOME,'RN',R.CNPJ_FORNECEDOR,R.NCM_PREFIXO,R.RESULTADO,R.PERCENTUAL_CREDITO,
       R.PRIORIDADE,N'Regra operacional informada na análise fiscal FERNANDES, competência 06/2026. Validar vigência na legislação do RN.',
       '2026-06-01',1
FROM REGRAS_FORNECEDOR R
WHERE NOT EXISTS (SELECT 1 FROM PRE_ANALISE_REGRA_ITEM E WHERE E.CODIGO = R.CODIGO);
GO

;WITH REGRAS_NCM AS (
    SELECT * FROM (VALUES
        ('38244000'),('32149000'),('68071000'),('35061090'),('40119090'),
        ('85444200'),('32082019'),('39095011'),('32089010'),('34053000'),
        ('32089029'),('82054000'),('82055900'),('96091000'),('39174090'),
        ('82031010'),('82052000'),('84672100'),('82075011')
    ) V(NCM)
)
INSERT INTO PRE_ANALISE_REGRA_ITEM
    (CODIGO,NOME,UF_DESTINO,NCM_PREFIXO,RESULTADO,PERCENTUAL_CREDITO,PRIORIDADE,
     FUNDAMENTO_LEGAL,VIGENCIA_INICIAL,ATIVA)
SELECT 'ST_RN_NCM_' + R.NCM,
       N'Item NCM ' + R.NCM + N' sujeito a ST no RN',
       'RN',R.NCM,'SEM_CREDITO_ST',0,30,
       N'Regra operacional informada na análise fiscal FERNANDES, competência 06/2026. Validar vigência na legislação do RN.',
       '2026-06-01',1
FROM REGRAS_NCM R
WHERE NOT EXISTS (SELECT 1 FROM PRE_ANALISE_REGRA_ITEM E WHERE E.CODIGO = 'ST_RN_NCM_' + R.NCM);
GO
