-- Histórico mensal de documentos, recebimentos e retenções informados pelos clientes.
-- O valor de caixa é sempre VALOR_RECEBIDO; retenções são mantidas apenas para análise.
IF OBJECT_ID('dbo.RECEBIMENTO_IMPORTACAO','U') IS NULL
CREATE TABLE dbo.RECEBIMENTO_IMPORTACAO (
    ID_RECEBIMENTO_IMPORTACAO INT IDENTITY PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    COMPETENCIA_ARQUIVO DATE NOT NULL,
    NOME_ARQUIVO NVARCHAR(255) NOT NULL,
    HASH_ARQUIVO VARCHAR(64) NOT NULL,
    NOME_ABA NVARCHAR(128) NOT NULL,
    LINHAS_LIDAS INT NOT NULL,
    TOTAL_FATURADO_ARQUIVO DECIMAL(18,2) NOT NULL,
    TOTAL_RECEBIDO_ARQUIVO DECIMAL(18,2) NOT NULL,
    TOTAL_RETENCOES_ARQUIVO DECIMAL(18,4) NOT NULL,
    QUANTIDADE_ALERTAS INT NOT NULL,
    IMPORTADO_EM DATETIME2 NOT NULL,
    CONSTRAINT FK_RECEBIMENTO_IMPORTACAO_EMPRESA FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
    CONSTRAINT UX_RECEBIMENTO_IMPORTACAO_COMPETENCIA UNIQUE(ID_EMPRESA,COMPETENCIA_ARQUIVO)
);

IF OBJECT_ID('dbo.RECEBIMENTO_DOCUMENTO','U') IS NULL
CREATE TABLE dbo.RECEBIMENTO_DOCUMENTO (
    ID_RECEBIMENTO_DOCUMENTO BIGINT IDENTITY PRIMARY KEY,
    ID_RECEBIMENTO_IMPORTACAO INT NOT NULL,
    CHAVE_NATURAL VARCHAR(64) NOT NULL,
    CLIENTE NVARCHAR(255) NOT NULL,
    DATA_EMISSAO DATE NULL,
    VALOR_FATURADO DECIMAL(18,2) NOT NULL,
    DESCONTO_INFORMADO DECIMAL(18,2) NULL,
    VALOR_ISS DECIMAL(18,4) NOT NULL,
    VALOR_PIS DECIMAL(18,4) NOT NULL,
    VALOR_COFINS DECIMAL(18,4) NOT NULL,
    VALOR_IR DECIMAL(18,4) NOT NULL,
    VALOR_CSLL DECIMAL(18,4) NOT NULL,
    VALOR_INSS DECIMAL(18,4) NOT NULL,
    VALOR_OUTROS DECIMAL(18,4) NOT NULL,
    CODIGO_SERVICO VARCHAR(50) NULL,
    NUMERO_NOTA VARCHAR(100) NULL,
    INDICADOR_RETENCOES_FEDERAIS NVARCHAR(255) NULL,
    INDICADOR_ISS NVARCHAR(255) NULL,
    LINHA_ORIGEM INT NOT NULL,
    CONSTRAINT FK_RECEBIMENTO_DOCUMENTO_IMPORTACAO FOREIGN KEY(ID_RECEBIMENTO_IMPORTACAO)
        REFERENCES RECEBIMENTO_IMPORTACAO(ID_RECEBIMENTO_IMPORTACAO) ON DELETE CASCADE
);

IF OBJECT_ID('dbo.RECEBIMENTO_MOVIMENTO','U') IS NULL
CREATE TABLE dbo.RECEBIMENTO_MOVIMENTO (
    ID_RECEBIMENTO_MOVIMENTO BIGINT IDENTITY PRIMARY KEY,
    ID_RECEBIMENTO_IMPORTACAO INT NOT NULL,
    CHAVE_NATURAL VARCHAR(64) NOT NULL,
    CLIENTE NVARCHAR(255) NOT NULL,
    DATA_RECEBIMENTO DATE NOT NULL,
    VALOR_RECEBIDO DECIMAL(18,2) NOT NULL,
    PARCELA VARCHAR(50) NULL,
    NOTAS_VINCULADAS NVARCHAR(1000) NULL,
    DATA_EMISSAO_REFERENCIA DATE NULL,
    RECEBIDO_ANTES_EMISSAO BIT NOT NULL,
    LINHA_ORIGEM INT NOT NULL,
    CONSTRAINT FK_RECEBIMENTO_MOVIMENTO_IMPORTACAO FOREIGN KEY(ID_RECEBIMENTO_IMPORTACAO)
        REFERENCES RECEBIMENTO_IMPORTACAO(ID_RECEBIMENTO_IMPORTACAO) ON DELETE CASCADE
);

IF OBJECT_ID('dbo.RECEBIMENTO_IMPORTACAO_LINHA','U') IS NULL
CREATE TABLE dbo.RECEBIMENTO_IMPORTACAO_LINHA (
    ID_RECEBIMENTO_IMPORTACAO_LINHA BIGINT IDENTITY PRIMARY KEY,
    ID_RECEBIMENTO_IMPORTACAO INT NOT NULL,
    NUMERO_LINHA INT NOT NULL,
    CONTEUDO_JSON NVARCHAR(MAX) NOT NULL,
    ALERTA NVARCHAR(1000) NULL,
    CONSTRAINT FK_RECEBIMENTO_LINHA_IMPORTACAO FOREIGN KEY(ID_RECEBIMENTO_IMPORTACAO)
        REFERENCES RECEBIMENTO_IMPORTACAO(ID_RECEBIMENTO_IMPORTACAO) ON DELETE CASCADE,
    CONSTRAINT UX_RECEBIMENTO_LINHA UNIQUE(ID_RECEBIMENTO_IMPORTACAO,NUMERO_LINHA)
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RECEBIMENTO_MOVIMENTO_DATA' AND object_id=OBJECT_ID('dbo.RECEBIMENTO_MOVIMENTO'))
    CREATE INDEX IX_RECEBIMENTO_MOVIMENTO_DATA ON dbo.RECEBIMENTO_MOVIMENTO(DATA_RECEBIMENTO,CHAVE_NATURAL);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RECEBIMENTO_DOCUMENTO_EMISSAO' AND object_id=OBJECT_ID('dbo.RECEBIMENTO_DOCUMENTO'))
    CREATE INDEX IX_RECEBIMENTO_DOCUMENTO_EMISSAO ON dbo.RECEBIMENTO_DOCUMENTO(DATA_EMISSAO,CHAVE_NATURAL);
