SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @Prefixos TABLE (NCM_PREFIXO NVARCHAR(8) NOT NULL PRIMARY KEY);
INSERT INTO @Prefixos (NCM_PREFIXO)
VALUES ('3209'),('4417'),('8207'),('8506'),('8507'),('8544'),
       ('40119090'),('40139000'),('32081010');

-- NCMs iniciados por 3917 não devem permanecer na regra de ST sem crédito.
UPDATE I
SET I.ID_PRE_ANALISE_REGRA_ITEM=NULL,
    I.CLASSIFICACAO='PENDENTE',
    I.NIVEL_CONFIANCA=NULL,
    I.CREDITO_PERMITIDO=NULL,
    I.DIFERENCA_CREDITO=NULL,
    I.JUSTIFICATIVA=N'NCM iniciado por 3917 retirado da regra de ST sem crédito.'
FROM PRE_ANALISE_SPED_ITEM I
JOIN PRE_ANALISE_REGRA_ITEM R
  ON R.ID_PRE_ANALISE_REGRA_ITEM=I.ID_PRE_ANALISE_REGRA_ITEM
WHERE R.CODIGO='ST_RN_PREFIXO_3917';

DELETE FROM PRE_ANALISE_REGRA_ITEM
WHERE CODIGO='ST_RN_PREFIXO_3917';

-- O NCM 69109000 dá direito a crédito e não deve permanecer na regra de ST sem crédito.
UPDATE I
SET I.ID_PRE_ANALISE_REGRA_ITEM=NULL,
    I.CLASSIFICACAO='CREDITO_PERMITIDO',
    I.NIVEL_CONFIANCA='ALTA',
    I.CREDITO_PERMITIDO=I.VL_ICMS,
    I.DIFERENCA_CREDITO=0,
    I.JUSTIFICATIVA=N'NCM 69109000 retirado da regra de ST sem crédito: o crédito de ICMS é permitido.'
FROM PRE_ANALISE_SPED_ITEM I
JOIN PRE_ANALISE_REGRA_ITEM R
  ON R.ID_PRE_ANALISE_REGRA_ITEM=I.ID_PRE_ANALISE_REGRA_ITEM
WHERE R.CODIGO='ST_RN_PREFIXO_69109000';

DELETE FROM PRE_ANALISE_REGRA_ITEM
WHERE CODIGO='ST_RN_PREFIXO_69109000';

UPDATE R
SET NOME=N'Produto ST sem crédito no RN - NCM iniciado por '+P.NCM_PREFIXO,
    UF_DESTINO='RN',
    NCM_PREFIXO=P.NCM_PREFIXO,
    CEST_PREFIXO=NULL,
    TERMOS_DESCRICAO=NULL,
    RESULTADO='SEM_CREDITO_ST',
    PERCENTUAL_CREDITO=0,
    PRIORIDADE=20,
    FUNDAMENTO_LEGAL=N'Regra fiscal para NCM iniciado por '+P.NCM_PREFIXO+N': produto sujeito à substituição tributária sem direito a crédito de ICMS no RN.',
    VIGENCIA_INICIAL='2026-01-01',
    VIGENCIA_FINAL=NULL,
    ATIVA=1
FROM PRE_ANALISE_REGRA_ITEM R
JOIN @Prefixos P ON R.CODIGO='ST_RN_PREFIXO_'+P.NCM_PREFIXO;

INSERT INTO PRE_ANALISE_REGRA_ITEM
    (CODIGO,NOME,UF_DESTINO,NCM_PREFIXO,RESULTADO,PERCENTUAL_CREDITO,PRIORIDADE,
     FUNDAMENTO_LEGAL,VIGENCIA_INICIAL,ATIVA)
SELECT 'ST_RN_PREFIXO_'+P.NCM_PREFIXO,
       N'Produto ST sem crédito no RN - NCM iniciado por '+P.NCM_PREFIXO,
       'RN',P.NCM_PREFIXO,'SEM_CREDITO_ST',0,20,
       N'Regra fiscal para NCM iniciado por '+P.NCM_PREFIXO+N': produto sujeito à substituição tributária sem direito a crédito de ICMS no RN.',
       '2026-01-01',1
FROM @Prefixos P
WHERE NOT EXISTS (
    SELECT 1 FROM PRE_ANALISE_REGRA_ITEM R
    WHERE R.CODIGO='ST_RN_PREFIXO_'+P.NCM_PREFIXO
);

-- Exceções às regras amplas que não devem ser classificadas como ST sem crédito.
UPDATE PRE_ANALISE_REGRA_ITEM
SET NCM_EXCECOES=CASE
        WHEN NULLIF(LTRIM(RTRIM(NCM_EXCECOES)),N'') IS NULL THEN N'85444900'
        ELSE NCM_EXCECOES+N';85444900'
    END
WHERE CODIGO='ST_RN_PREFIXO_8544'
  AND N';'+REPLACE(COALESCE(NCM_EXCECOES,N''),N' ',N'')+N';' NOT LIKE N'%;85444900;%';

UPDATE PRE_ANALISE_REGRA_ITEM
SET NCM_EXCECOES=CASE
        WHEN NULLIF(LTRIM(RTRIM(NCM_EXCECOES)),N'') IS NULL THEN N'85442000'
        ELSE NCM_EXCECOES+N';85442000'
    END
WHERE CODIGO='ST_RN_PREFIXO_8544'
  AND N';'+REPLACE(COALESCE(NCM_EXCECOES,N''),N' ',N'')+N';' NOT LIKE N'%;85442000;%';

UPDATE PRE_ANALISE_REGRA_ITEM
SET NCM_EXCECOES=CASE
        WHEN NULLIF(LTRIM(RTRIM(NCM_EXCECOES)),N'') IS NULL THEN N'85441100'
        ELSE NCM_EXCECOES+N';85441100'
    END
WHERE CODIGO='ST_RN_PREFIXO_8544'
  AND N';'+REPLACE(COALESCE(NCM_EXCECOES,N''),N' ',N'')+N';' NOT LIKE N'%;85441100;%';

UPDATE PRE_ANALISE_REGRA_ITEM
SET NCM_EXCECOES=CASE
        WHEN NULLIF(LTRIM(RTRIM(NCM_EXCECOES)),N'') IS NULL THEN N'82075019'
        ELSE NCM_EXCECOES+N';82075019'
    END
WHERE CODIGO='ST_RN_PREFIXO_8207'
  AND N';'+REPLACE(COALESCE(NCM_EXCECOES,N''),N' ',N'')+N';' NOT LIKE N'%;82075019;%';

UPDATE PRE_ANALISE_REGRA_ITEM
SET NCM_EXCECOES=CASE
        WHEN NULLIF(LTRIM(RTRIM(NCM_EXCECOES)),N'') IS NULL THEN N'82075011'
        ELSE NCM_EXCECOES+N';82075011'
    END
WHERE CODIGO='ST_RN_PREFIXO_8207'
  AND N';'+REPLACE(COALESCE(NCM_EXCECOES,N''),N' ',N'')+N';' NOT LIKE N'%;82075011;%';

DECLARE @NcmsRetirar TABLE (NCM NVARCHAR(8) NOT NULL PRIMARY KEY);
INSERT INTO @NcmsRetirar (NCM)
VALUES ('85444900'),('85442000'),('82075019'),('82075011'),
       ('85441100'),('39269090'),('96033000');

UPDATE I
SET I.ID_PRE_ANALISE_REGRA_ITEM=NULL,
    I.CLASSIFICACAO='PENDENTE',
    I.NIVEL_CONFIANCA=NULL,
    I.CREDITO_PERMITIDO=NULL,
    I.DIFERENCA_CREDITO=NULL,
    I.JUSTIFICATIVA=N'NCM retirado da regra de ST sem crédito.'
FROM PRE_ANALISE_SPED_ITEM I
JOIN @NcmsRetirar N
  ON RIGHT(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(COALESCE(I.NCM,N''))),'.',''),'-',''),' ',''),8)=N.NCM
JOIN PRE_ANALISE_REGRA_ITEM R
  ON R.ID_PRE_ANALISE_REGRA_ITEM=I.ID_PRE_ANALISE_REGRA_ITEM
WHERE R.RESULTADO='SEM_CREDITO_ST';

DELETE R
FROM PRE_ANALISE_REGRA_ITEM R
WHERE R.RESULTADO='SEM_CREDITO_ST'
  AND R.NCM_PREFIXO IN ('39269090','96033000');

-- Reclassifica análises já importadas para os NCMs completos incluídos nas regras.
-- O NCM 85444200 usa a regra já existente para o prefixo 8544.
DECLARE @NcmsReclassificar TABLE (
    NCM NVARCHAR(8) NOT NULL PRIMARY KEY,
    NCM_PREFIXO_REGRA NVARCHAR(8) NOT NULL
);
INSERT INTO @NcmsReclassificar (NCM,NCM_PREFIXO_REGRA)
VALUES ('40119090','40119090'),('40139000','40139000'),('32081010','32081010'),
       ('85444200','8544');

UPDATE I
SET I.ID_PRE_ANALISE_REGRA_ITEM=R.ID_PRE_ANALISE_REGRA_ITEM,
    I.CLASSIFICACAO='SEM_CREDITO_ST',
    I.NIVEL_CONFIANCA='ALTA',
    I.CREDITO_PERMITIDO=0,
    I.DIFERENCA_CREDITO=I.VL_ICMS,
    I.JUSTIFICATIVA=R.NOME+N'. O NCM está relacionado como produto sujeito à substituição tributária sem direito a crédito no RN.'+
        CASE WHEN NULLIF(LTRIM(RTRIM(R.FUNDAMENTO_LEGAL)),N'') IS NULL
             THEN N'' ELSE N' Fundamento: '+R.FUNDAMENTO_LEGAL END
FROM PRE_ANALISE_SPED_ITEM I
JOIN @NcmsReclassificar N
  ON RIGHT(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(COALESCE(I.NCM,N''))),'.',''),'-',''),' ',''),8)=N.NCM
JOIN PRE_ANALISE_REGRA_ITEM R
  ON R.CODIGO='ST_RN_PREFIXO_'+N.NCM_PREFIXO_REGRA;

COMMIT TRANSACTION;

SELECT COUNT(*) AS REGRAS_PREFIXO_ATIVAS
FROM PRE_ANALISE_REGRA_ITEM
WHERE CODIGO LIKE 'ST_RN_PREFIXO[_]%' AND ATIVA=1;
