SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @Prefixos TABLE (NCM_PREFIXO NVARCHAR(8) NOT NULL PRIMARY KEY);
INSERT INTO @Prefixos (NCM_PREFIXO)
VALUES ('3209'),('3917'),('4417'),('8207'),('8506'),('8507'),('8544');

UPDATE R
SET NOME=N'Produto ST sem crédito no RN - NCM iniciado por '+P.NCM_PREFIXO,
    UF_DESTINO='RN',
    NCM_PREFIXO=P.NCM_PREFIXO,
    CEST_PREFIXO=NULL,
    TERMOS_DESCRICAO=NULL,
    RESULTADO='SEM_CREDITO_ST',
    PERCENTUAL_CREDITO=0,
    PRIORIDADE=20,
    FUNDAMENTO_LEGAL=N'Regra fiscal para NCM iniciado por '+P.NCM_PREFIXO+N': produto sujeito à substituição tributária sem direito a crédito de ICMS no RN.',
    VIGENCIA_INICIAL='2026-01-01',
    VIGENCIA_FINAL=NULL,
    ATIVA=1
FROM PRE_ANALISE_REGRA_ITEM R
JOIN @Prefixos P ON R.CODIGO='ST_RN_PREFIXO_'+P.NCM_PREFIXO;

INSERT INTO PRE_ANALISE_REGRA_ITEM
    (CODIGO,NOME,UF_DESTINO,NCM_PREFIXO,RESULTADO,PERCENTUAL_CREDITO,PRIORIDADE,
     FUNDAMENTO_LEGAL,VIGENCIA_INICIAL,ATIVA)
SELECT 'ST_RN_PREFIXO_'+P.NCM_PREFIXO,
       N'Produto ST sem crédito no RN - NCM iniciado por '+P.NCM_PREFIXO,
       'RN',P.NCM_PREFIXO,'SEM_CREDITO_ST',0,20,
       N'Regra fiscal para NCM iniciado por '+P.NCM_PREFIXO+N': produto sujeito à substituição tributária sem direito a crédito de ICMS no RN.',
       '2026-01-01',1
FROM @Prefixos P
WHERE NOT EXISTS (
    SELECT 1 FROM PRE_ANALISE_REGRA_ITEM R
    WHERE R.CODIGO='ST_RN_PREFIXO_'+P.NCM_PREFIXO
);

COMMIT TRANSACTION;

SELECT COUNT(*) AS REGRAS_PREFIXO_ATIVAS
FROM PRE_ANALISE_REGRA_ITEM
WHERE CODIGO LIKE 'ST_RN_PREFIXO[_]%' AND ATIVA=1;
